import linked_list_InterQ as llInterQ

import test_Q1_RemoveDups
import test_Q2_Return_Kth_to_Last
import test_Q3_DeleteMiddleNode
import test_Q4_Partition
import test_Q5_Sumlist
import test_Q6_PalindromeCheck
import test_Q7_Intersection
import test_Q8_LoopDetection
